ALTER TYPE "AppModule" ADD VALUE IF NOT EXISTS 'COMERCIAL';
ALTER TYPE "ModuleRoleCode" ADD VALUE IF NOT EXISTS 'COMERCIAL_MANAGER';
ALTER TYPE "ModuleRoleCode" ADD VALUE IF NOT EXISTS 'COMERCIAL_SELLER';
ALTER TYPE "ModuleRoleCode" ADD VALUE IF NOT EXISTS 'COMERCIAL_VIEWER';
