import {
  AlertCircle,
  AlertTriangle,
  ArrowDown,
  ArrowUp,
  ArrowUpDown,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  CircleX,
  FileQuestion,
  Info,
  PackageOpen,
  Plus,
  Save,
  Search,
  SearchX,
  Settings,
  SlidersHorizontal,
  Trash2,
  X
} from 'lucide-react';

export const DS_ICONS = {
  alertDanger: CircleX,
  alertInfo: Info,
  alertSuccess: CheckCircle2,
  alertWarning: AlertTriangle,
  chevronDown: ChevronDown,
  filter: SlidersHorizontal,
  firstPage: ChevronsLeft,
  lastPage: ChevronsRight,
  next: ChevronRight,
  previous: ChevronLeft,
  emptyCreate: PackageOpen,
  emptyDefault: FileQuestion,
  emptyError: AlertCircle,
  emptySearch: SearchX,
  close: X,
  plus: Plus,
  save: Save,
  search: Search,
  sort: ArrowUpDown,
  sortAscending: ArrowUp,
  sortDescending: ArrowDown,
  settings: Settings,
  trash: Trash2
} as const;
