import {
  Archive,
  ArchiveRestore,
  AlertCircle,
  AlertTriangle,
  ArrowDown,
  ArrowUp,
  ArrowUpDown,
  CalendarDays,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  CircleX,
  FileText,
  FileQuestion,
  FolderKanban,
  Info,
  PackageOpen,
  Pencil,
  Plus,
  Save,
  Search,
  SearchX,
  Settings,
  SlidersHorizontal,
  Trash2,
  UserRound,
  UsersRound,
  X
} from 'lucide-react';

export const DS_ICONS = {
  archive: Archive,
  restore: ArchiveRestore,
  alertDanger: CircleX,
  alertInfo: Info,
  alertSuccess: CheckCircle2,
  alertWarning: AlertTriangle,
  calendar: CalendarDays,
  chevronDown: ChevronDown,
  filter: SlidersHorizontal,
  firstPage: ChevronsLeft,
  lastPage: ChevronsRight,
  next: ChevronRight,
  previous: ChevronLeft,
  emptyCreate: PackageOpen,
  emptyDefault: FileQuestion,
  emptyError: AlertCircle,
  emptySearch: SearchX,
  fileText: FileText,
  folder: FolderKanban,
  close: X,
  plus: Plus,
  edit: Pencil,
  save: Save,
  search: Search,
  sort: ArrowUpDown,
  sortAscending: ArrowUp,
  sortDescending: ArrowDown,
  settings: Settings,
  trash: Trash2,
  user: UserRound,
  users: UsersRound
} as const;
